server:
  port: 8080
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:mysql://sh-cynosdbmysql-grp-i4ykb8d4.sql.tencentcdb.com:25307
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: D9t7KmPn
  session:
    timeout: 86400
#    store-type: jdbc
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis-plus:

  configuration:
    mapUnderscoreToCamelCase: false
  global-config:
    db-config:
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
#spring.session.store-type